/**
 * Static city list for the standalone signup form. Not a DB table, not
 * fetched over the network — per docs/features/standalone-signup/spec.md
 * "City list": nothing about this list needs to be admin-editable or
 * queried at request time, this app has no runtime dependency on the
 * corporations repo/database. Contents are a one-time snapshot of the
 * full active-city list from the campaign's own production `cities`
 * table (86 active cities, read there on 2026-08-31) — not a curated
 * subset. If that list changes, this array needs a manual refresh; it
 * is not kept in sync automatically.
 */
export const CITIES = [
  "אום אל-פחם",
  "אופקים",
  "אור יהודה",
  "אור עקיבא",
  "אילת",
  "אלעד",
  "אשדוד",
  "אשקלון",
  "באקה אל-גרבייה",
  "באר יעקב",
  "באר שבע",
  "בית נטופה",
  "בית שאן ועמק מהעיינות",
  "בית שמש",
  "בני ברק",
  "בנימין",
  "בת ים",
  "גבעתיים",
  "גבעת שמואל",
  "גדרה",
  "גני תקווה",
  "דימונה",
  "הוד השרון",
  "הרצליה",
  "חדרה",
  "חולון",
  "חיפה",
  "חצור",
  "חריש",
  "טבריה / עמק בית שאן והעמקים",
  "טייבה",
  "טירה",
  "טירת כרמל",
  "יבנה",
  "יהודה",
  "יהוד-מונוסון",
  "יקנעם עילית",
  "ירוחם",
  "ירושלים",
  "כפר יונה",
  "כפר סבא",
  "כפר קאסם",
  "כפר קרע",
  "כרמיאל- משגב",
  "לוד",
  "מבשרת ציון",
  "מגדל העמק / עפולה",
  "מודיעין-מכבים-רעות",
  "מודיעין עילית",
  "מע'אר / מגזר הדרוזי",
  "מעלות-תרשיחא",
  "נהריה / גליל מערבי",
  "נוף הגליל",
  "נס ציונה",
  "נשר",
  "נתיבות",
  "נתניה",
  "עכו",
  "עפולה וכפר תבור",
  "ערד",
  "פתח תקווה",
  "צפת ומרום הגליל",
  "קלנסווה",
  "קצרין ורמת הגולן",
  "קריית אונו",
  "קריית אתא",
  "קריית ביאליק",
  "קריית גת",
  "קריית ים",
  "קריית מוצקין",
  "קריית מלאכי",
  "קריית שמונה / גליל מזרחי",
  "ראש העין",
  "ראשון לציון",
  "ראש פינה",
  "רהט",
  "רחובות",
  "רמלה",
  "רמת גן",
  "רמת השרון",
  "רעננה",
  "שדרות",
  "שוהם",
  "שומרון",
  "שלומי",
  "תל אביב-יפו",
] as const;
